# Generated by Django 3.1.7 on 2021-03-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data',
            field=models.CharField(max_length=100),
        ),
    ]
