# Generated by Django 3.1.7 on 2021-03-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20210325_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
